ResourceGroupName = "AveResGr1"
Location = "East US"
VirtualNetworkName = "AveVirNet1"
SubnetName = "sub1"
NetworkInterfaceName = "AveNetInt1"
IpConfigurationName = "AveIpConf"
ManagedDiskName = "AveManDisk1"
VirtualMachineName = "AveVM1"